### ISSUE TITLE
Gem fails to uncompress this particular file when compressed with the same gem (file included)

### ISSUE THREAD

**Issue by akshetpandey** [masamitsu-murase/seven_zip_ruby#12]
The file, [output01.txt](https://s3-us-west-2.amazonaws.com/ibassets/files/output01.txt) generates this file [output01.7z](https://s3-us-west-2.amazonaws.com/ibassets/files/output01.7z) when compressed using this gem. But both the 7z utility and the gem say that it is an invalid file when trying to decompress it.

``` ruby
StandardError: Invalid file format. open
    from /Users/akshet/.rvm/gems/ruby-2.1.5@mit_gemset/gems/seven_zip_ruby-1.2.4/lib/seven_zip_ruby/seven_zip_reader.rb:241:in `open_impl'
    from /Users/akshet/.rvm/gems/ruby-2.1.5@mit_gemset/gems/seven_zip_ruby-1.2.4/lib/seven_zip_ruby/seven_zip_reader.rb:241:in `open'
    from /Users/akshet/.rvm/gems/ruby-2.1.5@mit_gemset/gems/seven_zip_ruby-1.2.4/lib/seven_zip_ruby/seven_zip_reader.rb:258:in `open_file'
    from /Users/akshet/.rvm/gems/ruby-2.1.5@mit_gemset/gems/seven_zip_ruby-1.2.4/lib/seven_zip_ruby/seven_zip_reader.rb:140:in `open_file'
    from (irb):6
```

The error is present on Linux as well as OSX, it might be that the version of the native library has a bug present.

ruby: 2.1.5
seven_zip_ruby: 1.2.4

**Comment by masamitsu-murase** [comment]
Hi akshetpandey,

Thank you for the report!
I will check this issue after I go back to Japan in this weekend.

If possible, let me share the Ruby script which generates `output01.7z`.

Regards,
Murase

Akshet Pandey<notifications@github.com> wrote:

> The file, output01.txt
> <https://s3-us-west-2.amazonaws.com/ibassets/files/output01.txt>
> generates this file output01.7z
> <https://s3-us-west-2.amazonaws.com/ibassets/files/output01.7z> when
> compressed using this gem. But both the 7z utility and the gem say that it
> is an invalid file when trying to decompress it.
>
> StandardError: Invalid file format. open
>     from /Users/akshet/.rvm/gems/ruby-2.1.5@mit_gemset/gems/seven_zip_ruby-1.2.4/lib/seven_zip_ruby/seven_zip_reader.rb:241:in `open_impl'    from /Users/akshet/.rvm/gems/ruby-2.1.5@mit_gemset/gems/seven_zip_ruby-1.2.4/lib/seven_zip_ruby/seven_zip_reader.rb:241:in `open'    from /Users/akshet/.rvm/gems/ruby-2.1.5@mit_gemset/gems/seven_zip_ruby-1.2.4/lib/seven_zip_ruby/seven_zip_reader.rb:258:in `open_file'
>     from /Users/akshet/.rvm/gems/ruby-2.1.5@mit_gemset/gems/seven_zip_ruby-1.2.4/lib/seven_zip_ruby/seven_zip_reader.rb:140:in `open_file'    from (irb):6
>
> The error is present on Linux as well as OSX, it might be that the version
> of the native library has a bug present.
>
> ruby: 2.1.5
> seven_zip_ruby: 1.2.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/masamitsu-murase/seven_zip_ruby/issues/12>.
>


-- 
Mail:     masamitsu.murase@gmail.com
村瀬 昌満 (MURASE Masamitsu)

**Comment by akshetpandey** [comment]
```ruby
require 'rubygems'
require 'seven_zip_ruby'

dst = File.open("output.7z", File::BINARY|File::RDWR|File::CREAT|File::EXCL)
src_file = File.open("output01.txt")

SevenZipRuby::Writer.open(dst) do |szr|
  szr.add_file(src_file.path, as: "output01.txt")
end

output_file = File.open("output01_1.txt", File::RDWR|File::CREAT|File::EXCL)

SevenZipRuby::Reader.open_file(dst.path) do |szr|
  File.write(output_file.path, szr.extract_data(0))
end
```

**Comment by akshetpandey** [comment]
@masamitsu-murase : Any update on this issue?

**Comment by masamitsu-murase** [comment]
I'm sorry for the late reply.

I tried to reproduce this issue with Ubuntu 12.04, but I couldn't.
i.e. `StandardError: Invalid file format. open` was shown, but `7z` was able to parse `output.7z` properly.

By the way, it seems that your source code does not handle file cache properly.
Could you try to fix it as follows?
```ruby
require 'rubygems'
require 'seven_zip_ruby'

dst = File.open("output.7z", File::BINARY|File::RDWR|File::CREAT|File::EXCL)

SevenZipRuby::Writer.open(dst) do |szr|
  szr.add_file("output01.txt", as: "output01.txt")
end
dst.flush  # Add this line ####################

SevenZipRuby::Reader.open_file("output.7z") do |szr|
  File.write("output01_1.txt", szr.extract_data(0))
end
```

Regards,
Murase

**Comment by akshetpandey** [comment]
I am still unsure what is going to because my particular code doesn't have the issue of the need to flush the file and simply changing the content of the file that needs to be uncompressed fixes the issues.

But at this point, I have a feeling that the issues is probably somewhere in my code. You can close this issue if you think the problem is probably not with the native library.

**Comment by masamitsu-murase** [comment]
Let me close this issue.
Please re-open it if you find any cue.
