### ISSUE TITLE
Winzip compatible AES256 encrypted zip

### ISSUE THREAD

**Issue by sunilbg** [masamitsu-murase/seven_zip_ruby#16]
Hi,

Is there a way to use this library to generate a AES256 encrypted zip file, which can be opened with winzip.

**Comment by aaroalan** [comment]
Do you have the answer for this question? or Does this gem support AES Encryption even if need to be opened only with 7zip?

**Comment by masamitsu-murase** [comment]
This gem does not support AES for zip.
It supports 7-zip only.
