### ISSUE TITLE
building native extensions fail

### ISSUE THREAD

**Issue by microspino** [masamitsu-murase/seven_zip_ruby#19]
Hi thx for this gem 😘
I'm getting this error with **ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]** on OSX Yosemite 10.10.5 when i try to gem install it.
`....rbenv/versions/2.3.0/include/ruby-2.3.0/ruby/missing.h:256:5: error: use of undeclared identifier 'memset_s'`
Any clue?

**Comment by microspino** [comment]
Quick update: 
fails with **ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]**
and install fine with **ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]**

**Comment by wk8** [comment]
@microspino : should be fixed by https://github.com/masamitsu-murase/seven_zip_ruby/pull/20

**Comment by fanantoxa** [comment]
@microspino Linux part should be fixed on PR: https://github.com/masamitsu-murase/seven_zip_ruby/pulls

**Comment by fanantoxa** [comment]
@microspino, @masamitsu-murase This bugs were fixed on PR:
https://github.com/masamitsu-murase/seven_zip_ruby/pull/20
https://github.com/masamitsu-murase/seven_zip_ruby/pull/21
https://github.com/masamitsu-murase/seven_zip_ruby/pull/22
So I think we can close this issue

**Comment by masamitsu-murase** [comment]
As @fanantoxa said, this issue was solved by the other PRs.

Let me close this.
