### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by fanantoxa** [masamitsu-murase/seven_zip_ruby#23]
@masamitsu-murase When you going to make a next release?
And maybe want to update something before? I can try to help.

**Comment by fanantoxa** [comment]
@masamitsu-murase Could you let me know when you find a time for this?

**Comment by masamitsu-murase** [comment]
I have released v1.2.5.

I'm sorry for the inconvenience.

**Comment by fanantoxa** [comment]
@masamitsu-murase Really cool) Thank you)
