### ISSUE TITLE
LZMA SDK 19.00

### ISSUE THREAD

**Issue by ankane** [masamitsu-murase/seven_zip_ruby#29]
Hi, thanks for this great project 👍 I recommend it in one of my blog posts about [security](https://ankane.org/sensitive-data-rails#downloads).

It'd be great to update the [LZMA SDK](https://www.7-zip.org/sdk.html) from 9.20 to 19.00, which was released in February. There have been a number of fixes and improvements between the two versions - here's [the changelog](https://www.7-zip.org/history.txt).

**Comment by niloufar** [comment]
Hello.

Updated p7zip from 9.20 to 16.02. There is no Unit Test, and sufficient testing has not been performed. We have confirmed that the newly created test/test_seven_zip_reader.rb works. The confirmed OS is Manjaro Linux and Windows 10.

https://github.com/niloufar/seven_zip_ruby/tree/p7zip-16.02

If you think the updated p7zip content is untrustworthy, you can run p7zip/extract.sh to update the source to the new one. Execution requires p7zip-16.02 source archive.

**Comment by ankane** [comment]
Awesome, thanks @niloufar! That's a nice improvement. It seems like it'll be easiest to wait for p7zip to update to LZMA SDK 19.00 and then use a similar approach for this project.

**Comment by ankane** [comment]
Cleaning up stale issues
