### ISSUE TITLE
error while extracting zip file from link

### ISSUE THREAD

**Issue by nandini-klocrix** [masamitsu-murase/seven_zip_ruby#33]
Hi

I am trying to extract and decrypt the zip file using 7-zip format. But I am getting following error:
"StandardError: Invalid file format. open” I am sharing my piece of code
`require 'uri'`
 `def save_file(url)`
   ` open(url) do |file|`
      `SevenZipRuby::Reader.open(file, password: TRANSACTION_REPORT['password']) do |szr|`
        `szr.entries.each do |entry|`
          `TransactionReportFile.create(csv: entry.extract(entry.name))`
          `# call reconcile!`
        `end`
     ` end`
    `end`
  end`

**Comment by masamitsu-murase** [comment]
I cannot reproduce your issue on my side.
If you still have the issue, please simplify the reproduction step of the issue.
