### ISSUE TITLE
Gem compiles on Ruby 3.1.2 but no 7z.so is installed

### ISSUE THREAD

**Issue by contentfree** [masamitsu-murase/seven_zip_ruby#38]
This leads to the inability to use the Gem due to:
```
/usr/local/bundle/gems/bundler-2.3.4/lib/bundler/runtime.rb:63:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'seven_zip_ruby'.
Gem Load Error is: Failed to find 7z.dll or 7z.so
```

Where should the 7z.so be located? It's nowhere in `/usr/local/bundle/ruby/` (I see 7z.dll in `/usr/local/bundle/ruby/3.1.0/gems/seven_zip_ruby-1.3.0/lib/seven_zip_ruby/`)

This is on Ubuntu Linux with bundler 2.3.4.

**Comment by contentfree** [comment]
I'm also getting this with Ruby 2.7.4. Anything specific I can look for?

**Comment by contentfree** [comment]
I went back and retried the docker build (and with bundler 2.2.24) and that seemed to work. Then went back and built an image the same way as I originally had and it continued to work. (Shaking my fist at Docker!)

Closing.

**Comment by microstudi** [comment]
Manually installing `p7zip-full`and copying the library `7z.so` also works, but I think it should be fixed. Maybe we should leave this issue opened.

```
apt install p7zip-full
cp /usr/lib/p7zip/7z.so /usr/local/bundle/gems/seven_zip_ruby-1.3.0/lib/seven_zip_ruby/
```
or

```
ln -s /usr/lib/p7zip/7z.so /usr/local/bundle/gems/seven_zip_ruby-1.3.0/lib/seven_zip_ruby/7z.so
```
